### ISSUE TITLE
How to do it on custom data?

### ISSUE THREAD

**Issue by YiChenCityU** [CyberAgentAILab/SuperNormal#7]
Hi, Could you provide some information about reconstruct on custom data? And how to get normal maps? Thanks very much.

**Comment by flow-specter** [comment]
Same question

**Comment by xucao-42** [comment]
Hi, 
To obtain the normal maps, follow the instructions in this CVPR'23 work:
https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023
In short, at each viewpoint, you need to capture a set of images under varying illumination (from my experience, about 10 images per view is sufficient). This can be realized by moving a handheld light source. Input the images of each view to the  CVPR'23 work should output a good quality normal map. 

Repeat this process for each view, and you can get multi-view normal maps. Since you also captured rgb images, pick one from each view to calibrate the camera parameters.  We found Colmap usually fails for such a capture setup, but MetaShape performs more robustly.

We recommend placing the object on a turntable, but moving the camera and tripod should also be fine. Ensure there is a textured background static to the target object or use markers to increase the success rate of camera calibration.

**Comment by xucao-42** [comment]
Instructions on preparing custom data is available [here](https://github.com/CyberAgentAILab/SuperNormal/tree/main/data_capture_and_preprocessing).

**Comment by zxbzhineng** [comment]
@xucao-42 Hello, my original data consists of drone images of a scene and camera parameters. I only want to reconstruct one building in the scene. I cropped the building from each image and then offset the principal point of the image in the camera parameters. The final reconstruction result is not good. My current analysis shows that the reasons are: 1. The principal point has a negative value, and 2. The principal point is significantly offset from the cropped image. Could you help me solve this problem? Thank you very much.
